"""empty message

Revision ID: 627221f0db0e
Revises: 867c2d85f190
Create Date: 2022-05-23 17:53:43.279256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627221f0db0e'
down_revision = '867c2d85f190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fav_starships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('starships_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['starships_id'], ['starships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fav_starships')
    # ### end Alembic commands ###
